<?php

use StackMonitor\Agent\NpmPackages;

function npmProject(array $files): string
{
    $dir = sys_get_temp_dir().'/sm-npm-'.bin2hex(random_bytes(4));
    mkdir($dir);

    foreach ($files as $name => $content) {
        file_put_contents($dir.'/'.$name, is_array($content) ? json_encode($content) : $content);
    }

    return $dir;
}

afterEach(function () {
    foreach (glob(sys_get_temp_dir().'/sm-npm-*') ?: [] as $dir) {
        array_map('unlink', glob($dir.'/*') ?: []);
        rmdir($dir);
    }
});

it('reports nothing for a project without package.json', function () {
    expect((new NpmPackages(npmProject([])))->report())->toBeNull();
});

it('says so when the lockfile is missing', function () {
    $report = (new NpmPackages(npmProject(['package.json' => ['dependencies' => ['axios' => '^1.7.0']]])))->report();

    expect($report)->toBe(['lockfile' => null, 'truncated' => false, 'packages' => []]);
});

it('reads all packages of a package-lock.json v3, transitive and nested ones too', function () {
    $dir = npmProject([
        'package.json' => ['dependencies' => ['axios' => '^1.7.0'], 'devDependencies' => ['vite' => '^5.0.0']],
        'package-lock.json' => [
            'lockfileVersion' => 3,
            'packages' => [
                '' => ['name' => 'app', 'dependencies' => ['axios' => '^1.7.0']],
                'node_modules/axios' => ['version' => '1.7.2'],
                'node_modules/follow-redirects' => ['version' => '1.15.6'],
                'node_modules/vite' => ['version' => '5.2.0', 'dev' => true],
                'node_modules/@esbuild/linux-x64' => ['version' => '0.20.2', 'dev' => true, 'optional' => true],
                'node_modules/rollup' => ['version' => '4.0.0', 'devOptional' => true],
                'node_modules/vite/node_modules/follow-redirects' => ['version' => '1.14.0', 'dev' => true],
                'node_modules/local-lib' => ['resolved' => 'packages/local-lib', 'link' => true],
                'packages/local-lib' => ['version' => '0.1.0'],
            ],
        ],
    ]);

    expect((new NpmPackages($dir))->report())->toBe([
        'lockfile' => 'package-lock.json',
        'truncated' => false,
        'packages' => [
            ['name' => '@esbuild/linux-x64', 'version' => '0.20.2', 'dev' => true],
            ['name' => 'axios', 'version' => '1.7.2', 'dev' => false],
            ['name' => 'follow-redirects', 'version' => '1.14.0', 'dev' => true],
            ['name' => 'follow-redirects', 'version' => '1.15.6', 'dev' => false],
            ['name' => 'rollup', 'version' => '4.0.0', 'dev' => true],
            ['name' => 'vite', 'version' => '5.2.0', 'dev' => true],
        ],
    ]);
});

it('reads the nested dependencies of a package-lock.json v1', function () {
    $dir = npmProject([
        'package.json' => ['dependencies' => ['lodash' => '^4.17.0']],
        'package-lock.json' => [
            'lockfileVersion' => 1,
            'dependencies' => [
                'lodash' => ['version' => '4.17.20'],
                'webpack' => [
                    'version' => '4.46.0',
                    'dev' => true,
                    'dependencies' => ['lodash' => ['version' => '4.17.15', 'dev' => true]],
                ],
            ],
        ],
    ]);

    expect((new NpmPackages($dir))->report()['packages'])->toBe([
        ['name' => 'lodash', 'version' => '4.17.15', 'dev' => true],
        ['name' => 'lodash', 'version' => '4.17.20', 'dev' => false],
        ['name' => 'webpack', 'version' => '4.46.0', 'dev' => true],
    ]);
});

it('counts a package as production when it is installed for both', function () {
    $dir = npmProject([
        'package.json' => [],
        'package-lock.json' => [
            'lockfileVersion' => 3,
            'packages' => [
                'node_modules/a/node_modules/lodash' => ['version' => '4.17.21', 'dev' => true],
                'node_modules/b/node_modules/lodash' => ['version' => '4.17.21'],
            ],
        ],
    ]);

    expect((new NpmPackages($dir))->report()['packages'])->toBe([
        ['name' => 'lodash', 'version' => '4.17.21', 'dev' => false],
    ]);
});

it('reads a yarn.lock v1, dev only for direct devDependencies', function () {
    $lock = <<<'YARN'
        # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
        # yarn lockfile v1


        "@vitejs/plugin-vue@^5.0.0":
          version "5.0.4"
          resolved "https://registry.yarnpkg.com/@vitejs/plugin-vue/-/plugin-vue-5.0.4.tgz"

        axios@^1.6.0, axios@^1.7.0:
          version "1.7.2"
          dependencies:
            follow-redirects "^1.15.6"

        follow-redirects@^1.15.6:
          version "1.15.6"
        YARN;
    $dir = npmProject([
        'package.json' => ['dependencies' => ['axios' => '^1.7.0'], 'devDependencies' => ['@vitejs/plugin-vue' => '^5.0.0']],
        'yarn.lock' => $lock,
    ]);

    expect((new NpmPackages($dir))->report())->toBe([
        'lockfile' => 'yarn.lock',
        'truncated' => false,
        'packages' => [
            ['name' => '@vitejs/plugin-vue', 'version' => '5.0.4', 'dev' => true],
            ['name' => 'axios', 'version' => '1.7.2', 'dev' => false],
            ['name' => 'follow-redirects', 'version' => '1.15.6', 'dev' => false],
        ],
    ]);
});

it('reads a yarn berry lockfile and skips workspaces', function () {
    $lock = <<<'YARN'
        __metadata:
          version: 8
          cacheKey: 10c0

        "app@workspace:.":
          version: 0.0.0-use.local
          resolution: "app@workspace:."

        "axios@npm:^1.7.0":
          version: 1.7.2
          resolution: "axios@npm:1.7.2"

        "@types/node@npm:^20.0.0, @types/node@npm:^20.1.0":
          version: 20.11.0
          resolution: "@types/node@npm:20.11.0"
        YARN;
    $dir = npmProject(['package.json' => [], 'yarn.lock' => $lock]);

    expect((new NpmPackages($dir))->report()['packages'])->toBe([
        ['name' => '@types/node', 'version' => '20.11.0', 'dev' => false],
        ['name' => 'axios', 'version' => '1.7.2', 'dev' => false],
    ]);
});

it('reads a pnpm lockfile of version 6 with its dev flags', function () {
    $lock = <<<'PNPM'
        lockfileVersion: '6.0'

        dependencies:
          axios:
            specifier: ^1.7.0
            version: 1.7.2

        packages:

          /axios@1.7.2:
            resolution: {integrity: sha512-abc}
            dev: false

          /@babel/core@7.24.0:
            resolution: {integrity: sha512-def}
            dev: true

          /vite@5.2.0(@types/node@20.11.0):
            resolution: {integrity: sha512-ghi}
            dev: true
        PNPM;
    $dir = npmProject(['package.json' => [], 'pnpm-lock.yaml' => $lock]);

    expect((new NpmPackages($dir))->report())->toBe([
        'lockfile' => 'pnpm-lock.yaml',
        'truncated' => false,
        'packages' => [
            ['name' => '@babel/core', 'version' => '7.24.0', 'dev' => true],
            ['name' => 'axios', 'version' => '1.7.2', 'dev' => false],
            ['name' => 'vite', 'version' => '5.2.0', 'dev' => true],
        ],
    ]);
});

it('reads a pnpm lockfile of version 9, dev only for direct devDependencies', function () {
    $lock = <<<'PNPM'
        lockfileVersion: '9.0'

        importers:

          .:
            dependencies:
              axios:
                specifier: ^1.7.0
                version: 1.7.2

        packages:

          '@babel/core@7.24.0':
            resolution: {integrity: sha512-def}

          axios@1.7.2:
            resolution: {integrity: sha512-abc}

        snapshots:

          axios@1.7.2:
            dependencies:
              follow-redirects: 1.15.6
        PNPM;
    $dir = npmProject([
        'package.json' => ['devDependencies' => ['@babel/core' => '^7.24.0']],
        'pnpm-lock.yaml' => $lock,
    ]);

    expect((new NpmPackages($dir))->report()['packages'])->toBe([
        ['name' => '@babel/core', 'version' => '7.24.0', 'dev' => true],
        ['name' => 'axios', 'version' => '1.7.2', 'dev' => false],
    ]);
});

it('prefers package-lock.json when there are several lockfiles', function () {
    $dir = npmProject([
        'package.json' => [],
        'package-lock.json' => ['lockfileVersion' => 3, 'packages' => ['node_modules/a' => ['version' => '1.0.0']]],
        'yarn.lock' => "b@^1.0.0:\n  version \"1.0.0\"\n",
    ]);

    expect((new NpmPackages($dir))->report()['lockfile'])->toBe('package-lock.json');
});

it('reports an unreadable lockfile with no packages', function () {
    $dir = npmProject(['package.json' => [], 'package-lock.json' => '{not json']);

    expect((new NpmPackages($dir))->report())->toBe(['lockfile' => 'package-lock.json', 'truncated' => false, 'packages' => []]);
});

it('cuts the list at the limit and says so', function () {
    $packages = [];

    for ($i = 0; $i < 5; $i++) {
        $packages["node_modules/p{$i}"] = ['version' => '1.0.0'];
    }

    $dir = npmProject(['package.json' => [], 'package-lock.json' => ['lockfileVersion' => 3, 'packages' => $packages]]);
    $report = (new NpmPackages($dir, limit: 3))->report();

    expect($report['truncated'])->toBeTrue()
        ->and($report['packages'])->toHaveCount(3);
});

it('leaves out names and versions the schema would reject', function () {
    $dir = npmProject([
        'package.json' => [],
        'package-lock.json' => ['lockfileVersion' => 3, 'packages' => [
            'node_modules/'.str_repeat('a', 215) => ['version' => '1.0.0'],
            'node_modules/b' => ['version' => str_repeat('1', 101)],
            'node_modules/c' => ['version' => ''],
            'node_modules/d' => ['version' => '1.0.0'],
        ]],
    ]);

    expect((new NpmPackages($dir))->report()['packages'])->toBe([['name' => 'd', 'version' => '1.0.0', 'dev' => false]]);
});
